2024-02-28 11:11:37,628 INFO    MainThread:4114372 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2024-02-28 11:11:37,629 INFO    MainThread:4114372 [wandb_setup.py:_flush():76] Configure stats pid to 4114372
2024-02-28 11:11:37,629 INFO    MainThread:4114372 [wandb_setup.py:_flush():76] Loading settings from /home/mikail/.config/wandb/settings
2024-02-28 11:11:37,629 INFO    MainThread:4114372 [wandb_setup.py:_flush():76] Loading settings from /rdma/vast-rdma/vast/fiete/mikail/graph-reps/pytorch_implementation/wandb/settings
2024-02-28 11:11:37,629 INFO    MainThread:4114372 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-28 11:11:37,629 INFO    MainThread:4114372 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-28 11:11:37,631 INFO    MainThread:4114372 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'pytorch_implementation/train_graphs.py', 'program_abspath': '/rdma/vast-rdma/vast/fiete/mikail/graph-reps/pytorch_implementation/train_graphs.py', 'program': '/rdma/vast-rdma/vast/fiete/mikail/graph-reps/pytorch_implementation/train_graphs.py'}
2024-02-28 11:11:37,632 INFO    MainThread:4114372 [wandb_init.py:_log_setup():528] Logging user logs to /rdma/vast-rdma/vast/fiete/mikail/graph-reps/pytorch_implementation/wandb/run-20240228_111137-n03n4f8x/logs/debug.log
2024-02-28 11:11:37,634 INFO    MainThread:4114372 [wandb_init.py:_log_setup():529] Logging internal logs to /rdma/vast-rdma/vast/fiete/mikail/graph-reps/pytorch_implementation/wandb/run-20240228_111137-n03n4f8x/logs/debug-internal.log
2024-02-28 11:11:37,635 INFO    MainThread:4114372 [wandb_init.py:init():568] calling init triggers
2024-02-28 11:11:37,636 INFO    MainThread:4114372 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {}
2024-02-28 11:11:37,637 INFO    MainThread:4114372 [wandb_init.py:init():618] starting backend
2024-02-28 11:11:37,638 INFO    MainThread:4114372 [wandb_init.py:init():622] setting up manager
2024-02-28 11:11:37,643 INFO    MainThread:4114372 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-28 11:11:37,649 INFO    MainThread:4114372 [wandb_init.py:init():628] backend started and connected
2024-02-28 11:11:37,657 INFO    MainThread:4114372 [wandb_init.py:init():720] updated telemetry
2024-02-28 11:11:37,707 INFO    MainThread:4114372 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-28 11:11:38,020 INFO    MainThread:4114372 [wandb_run.py:_on_init():2220] communicating current version
2024-02-28 11:11:38,127 INFO    MainThread:4114372 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.16.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-02-28 11:11:38,127 INFO    MainThread:4114372 [wandb_init.py:init():804] starting run threads in backend
2024-02-28 11:11:44,504 WARNING MainThread:4114372 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/om2/user/mikail/miniconda3/envs/rlincontext/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/om2/user/mikail/miniconda3/envs/rlincontext/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 815, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/om2/user/mikail/miniconda3/envs/rlincontext/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/om2/user/mikail/miniconda3/envs/rlincontext/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/om2/user/mikail/miniconda3/envs/rlincontext/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/om2/user/mikail/miniconda3/envs/rlincontext/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/om2/user/mikail/miniconda3/envs/rlincontext/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-02-28 11:11:50,073 WARNING MsgRouterThr:4114372 [router.py:message_loop():77] message_loop has been closed
