4.1217451095581055
1.9196494817733765
0.5971256494522095
0.4204101264476776
0.3629099130630493
0.32762378454208374
0.29456308484077454
0.2695033550262451
0.2417294830083847
0.21479621529579163
0.2037985622882843
0.1836753636598587
0.1669701337814331
0.1484312117099762
0.14083331823349
0.12785974144935608
0.12348023056983948
0.11181432008743286
0.10600584745407104
0.09638030081987381
0.08898027241230011
0.08284712582826614
0.07984607666730881
0.0687243789434433
0.06945132464170456
0.06848368793725967
0.06388267874717712
0.059325456619262695
0.05977720767259598
0.05901249125599861
0.052563998848199844
0.05326008051633835
0.054432496428489685
0.04820628464221954
0.04585455358028412
0.045128341764211655
0.04561886936426163
0.03734486177563667
0.04596821218729019
0.04469834268093109
0.04570229351520538
0.04555613920092583
0.04597493261098862
0.0359073281288147
0.04088745266199112
0.0435262992978096
0.0470476932823658
0.04355184733867645
0.03730190545320511
0.040490176528692245
Traceback (most recent call last):
  File "/rdma/vast-rdma/vast/fiete/mikail/graph-reps/pytorch_implementation/train_graphs.py", line 163, in <module>
    np.savez(prefix + "/iter%d"%run, np.array(losses), index , np.array(bias1s), np.array(bias2s), np.array([best_loss]), np.array(tprobs))
NameError: name 'run' is not defined
Traceback (most recent call last):
  File "/rdma/vast-rdma/vast/fiete/mikail/graph-reps/pytorch_implementation/train_graphs.py", line 163, in <module>
    np.savez(prefix + "/iter%d"%run, np.array(losses), index , np.array(bias1s), np.array(bias2s), np.array([best_loss]), np.array(tprobs))
NameError: name 'run' is not defined
